CREATE TABLE carts(
  	id INT AUTO_INCREMENT PRIMARY KEY,
	id_product INT NOT NULL,  
  	quantity INT NOT NULL, 
  	price_total INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
