CREATE TABLE addresses(
  	id INT AUTO_INCREMENT PRIMARY KEY,
	village VARCHAR(255) NOT NULL,  
    subdistrict VARCHAR(255) NOT NULL,  
    city VARCHAR(255) NOT NULL,
    province VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);