CREATE TABLE invoice(
  	id INT AUTO_INCREMENT PRIMARY KEY,
	id_cart INT NOT NULL,  
  	diskon INT, 
  	id_address INT NOT NULL,
	user_id INT NOT NULL,
    price_total_invoice INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
